version: '3.8'

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      TZ: 'Asia/Tokyo'
    cap_add:
      - SYS_NICE  
    volumes:
      - ./db.mysql:/var/lib/mysql
    env_file:
      - .env.development
  backend:
    build: 
      context: .
      dockerfile: ./{project-name}/Dockerfile.development
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./{project-name}:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint:
      - dockerize
      - -timeout
      - 120s
      - -wait
      - tcp://db:3306
    env_file:
      - .env.development
volumes:
  local_info:
