version: '3.8'
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      TZ: 'Asia/Tokyo'
    cap_add:
      - SYS_NICE  
    volumes:
      - ./db.mysql:/var/lib/mysql
    env_file:
      - .env.development
